config/routes.rb
Railsg::Application.routes.draw do
  resources :comments, only: [:create, :destroy]

  get "pages/info"
  resources :ideas
  root 'ideas#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	mount_uploader :picture, PictureUploader
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.idea, notice: 'Comment was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def index
    @ideas = Idea.all
  end

  def show
    @comment = @idea.comments.build
  end

  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private

    def set_idea
      @idea = Idea.find(params[:id])
    end


    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class="col-sm-3"></div>

    <div class="col-sm-6">
      <div class="col-sm-12">
        <%= f.text_field :user_name, class: "form-control", placeholder: "Username" %><br>
      </div>
      
      <div class="col-sm-12">
        <%= f.text_area :body, class: "form-control", placeholder: "Comment"  %><br>
      </div>

      <%= f.hidden_field :idea_id %>

      <div class="col-sm-12">
        <%= f.submit 'Add', class: 'btn btn-primary' %>
      </div>
    </div>

    <div class="col-sm-3"> </div>

  </div>

<% end %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class='row'>
  <div class="col-md-2"></div>

  <div class="col-md-7">
    <%= link_to 'New Idea', new_idea_path, class: "btn btn-default"%>

    <button type="button" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Vivamus
    sagittis lacus vel augue laoreet rutrum faucibus.">
      New Idea
    </button>
  </div>

  <div class="col-md-2"></div>
</div>

<div class='row'>
  <div class="col-md-2"></div>

  <div class="col-md-7">
  <h1 class='title'>Ideas</h1>
    <% @ideas.each do |idea| %>
      <div class='jumbotron'>
        <%= link_to(image_tag(idea.picture.thumb, title: idea.name), idea) %>
        <br>
        <%= link_to 'Edit', edit_idea_path(idea) %>
        <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
        <br>
        <%= idea.description %>
        
        <% if idea.comments.present? %>
          <br>
          <% if idea.comments.count == 1 %>
              <%= idea.comments.count %> <span>comment</span>
          <% elsif %>
              <%= idea.comments.count %> <span>comments</span>
          <% else %>
          <% end %>
        <% end %>
      </div>
      <br>
    <% end %>
  </div>

  <div class="col-md-2"></div>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    
    <div class="col-md-8">
      <%= image_tag(@idea.picture.url, width: 600) if @idea.picture.present? %>
    </div>
    <div class="col-md-4">
      <p><%= time_ago_in_words(@idea['created_at']) %> ago</p>
      <p><%= @idea.description %></p>

      <% @idea.comments.each do |comment| %>
        <p>
          <strong><%= comment.user_name %></strong>
          <p><%= comment.body %></p>
        </p>
      <% end %>
      <br>
      <%= render 'comments/form' %>
    </div>

  </div>
  
  <div class="col-md-1"></div>


  <%= link_to 'Edit', edit_idea_path(@idea) %> |
  <%= link_to 'Back', ideas_path %>

</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Mumblr.', '/', class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="inactive"><%= link_to 'Info', pages_info_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mumblr.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- fixes responsive design behavior on mobile devices -->
  <meta name='viewport' content="width=device-width, inital-scale=1.0">
</head>
<body>
	
	<%= render '/layouts/nav' %>
	
	<div class='container'>
		<%= yield %>
	</div>
	
	<%= render '/layouts/footer' %>

</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>